apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
    
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: MyApp
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: MyApp
        
        track: stable
    spec:
      containers:
      - name: nginx
        image: "gcr.io/project-test-01-282013/pippo:v2"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]